export const UPDATE_POSTS = "UPDATE_POSTS";
export const UPDATE_USERS = "UPDATE_USERS";
export const UPDATE_USER_TRIPS = "UPDATE_USER_TRIPS";
export const ADD_USER_TRIP = "ADD_USER_TRIP";
export const SHOW_TIMELINE = "SHOW_TIMELINE";
export const UPDATE_CURRENT_TRIP_NAME = "UPDATE_CURRENT_TRIP_NAME";
export const UPDATE_CURRENT_TRIP_ID = "UPDATE_CURRENT_TRIP_ID";
